import React from 'react';

export default function Terms() {
  return (
    <main style={{ paddingTop: 64, minHeight: '100vh', background: 'var(--white)' }}>
      <div className="container" style={{ maxWidth: 720, padding: 'clamp(3rem, 8vw, 5rem) clamp(1.25rem, 5vw, 2rem)' }}>
        <div style={{ fontSize: '0.72rem', letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--gold)', marginBottom: '0.75rem' }}>✦ Legal</div>
        <h1 style={{ fontFamily: 'var(--serif)', fontSize: 'clamp(2rem, 5vw, 3rem)', letterSpacing: '-0.02em', marginBottom: '2.5rem' }}>Terms of Use</h1>
        {[
          { title: 'Acceptance', body: 'By using BrandForge AI, you agree to these terms. If you do not agree, please do not use the service.' },
          { title: 'Use of generated content', body: 'All brand concepts generated by BrandForge AI are yours to use freely, including for commercial purposes. No attribution to BrandForge is required.' },
          { title: 'Fair use', body: 'The service is free and intended for genuine brand creation. Automated scraping, bulk generation, or abuse of the free tier may result in access being restricted.' },
          { title: 'No warranties', body: 'BrandForge AI is provided "as is". We do not guarantee that generated brand names, taglines, or designs are free from trademark conflicts. It is your responsibility to verify that your brand assets do not infringe on existing trademarks.' },
          { title: 'Limitation of liability', body: 'BrandForge AI is not liable for any damages arising from use of the service or the brand assets generated.' },
          { title: 'Changes', body: 'We may update these terms at any time. Continued use of the service constitutes acceptance of the updated terms.' },
          { title: 'Contact', body: 'For any questions about these terms, email us at legal@brandforge.ai' },
        ].map(s => (
          <div key={s.title} style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontFamily: 'var(--serif)', fontSize: '1.2rem', marginBottom: '0.6rem' }}>{s.title}</h2>
            <p style={{ fontSize: '0.95rem', color: 'var(--gray)', lineHeight: 1.8 }}>{s.body}</p>
          </div>
        ))}
        <p style={{ fontSize: '0.8rem', color: 'var(--gray)', borderTop: '1px solid var(--gray-light)', paddingTop: '1.5rem', marginTop: '1rem' }}>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
      </div>
    </main>
  );
}
